source 'http://rubygems.org'

gem 'middleman', '~> 3.3.7'
gem 'middleman-blog'
gem 'builder'
gem 'redcarpet'
gem 'middleman-syntax'
gem 'middleman-search_engine_sitemap'
gem 'nokogiri'
gem 'middleman-livereload'
